/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_staff;

import funiture_system.GetInformation;
import funiture_system.Main_App;
import main_staff.manage_category_3.Category;
import main_staff.manage_customer_2.CustomerFrame;
import main_staff.manage_feedback_2.Feedbackmanager;
import main_staff.manage_product_3.Product;
import main_staff.manage_promotion.Promotion;

/**
 *
 * @author Duy Nguyen
 */
public class Main_Staff extends javax.swing.JFrame {

    /**
     * Creates new form Main_Staff
     */
    public Main_Staff() {
        initComponents();
        lbName.setText(GetInformation.name);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        btnApp = new javax.swing.JButton();
        lbName = new javax.swing.JLabel();
        btnPromotion = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setResizable(false);
        setSize(new java.awt.Dimension(770, 440));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Staff");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 60, 100, 48);

        btnCustomer.setBackground(new java.awt.Color(0, 238, 238));
        btnCustomer.setText("Manage Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomer);
        btnCustomer.setBounds(310, 210, 140, 41);

        btnFeedback.setBackground(new java.awt.Color(0, 238, 238));
        btnFeedback.setText("Manage Feedback");
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnFeedback);
        btnFeedback.setBounds(510, 210, 140, 39);

        btnApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funiture_system/img/account.jpg"))); // NOI18N
        btnApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppActionPerformed(evt);
            }
        });
        getContentPane().add(btnApp);
        btnApp.setBounds(670, 30, 40, 40);
        getContentPane().add(lbName);
        lbName.setBounds(640, 80, 120, 20);

        btnPromotion.setBackground(new java.awt.Color(0, 238, 238));
        btnPromotion.setText("Manage Promotion");
        btnPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromotionActionPerformed(evt);
            }
        });
        getContentPane().add(btnPromotion);
        btnPromotion.setBounds(110, 210, 140, 40);

        btnCategory.setBackground(new java.awt.Color(0, 238, 238));
        btnCategory.setText("Manage Category");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategory);
        btnCategory.setBounds(430, 280, 140, 40);

        btnProduct.setBackground(new java.awt.Color(0, 238, 238));
        btnProduct.setText("Manage Product");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduct);
        btnProduct.setBounds(200, 280, 140, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        CustomerFrame customer = new CustomerFrame();
        this.dispose();
        customer.show();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        Feedbackmanager feedback = new Feedbackmanager();
        this.dispose();
        feedback.show();
    }//GEN-LAST:event_btnFeedbackActionPerformed

    private void btnAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppActionPerformed
        Main_App app = new Main_App();
        this.dispose();
        app.show();
    }//GEN-LAST:event_btnAppActionPerformed

    private void btnPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromotionActionPerformed
        Promotion promotion = new Promotion();
        this.dispose();
        promotion.show();
    }//GEN-LAST:event_btnPromotionActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        Category category = new Category();
        this.dispose();
        category.show();
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        Product product = new Product();
        this.dispose();
        product.show();
    }//GEN-LAST:event_btnProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApp;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnPromotion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
